#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Jacurutu Productions
tagline: Passable design at dirtbag prices!
email: jacurutuproductions@gmail.com
description: "Jacurutu Productions - Decent design on a budget for broke-ass bands"

exclude:
  - "*.bak"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://www.github.com/eigenbrot

# Build settings
markdown: kramdown
permalink: pretty